apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
      annotations:
        kubernetes.io/change-cause: "amigoscode/kubernetes:customer-v1"
    spec:
      containers:
      - name: customer
        image: "amigoscode/kubernetes:cutomer-v1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
