apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: auth-secret
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHViLmRvY2tlci5jb20iOiB7InVzZXJuYW1lIjogIndpbm1vcnJlIiwgInBhc3N3b3JkIjogIkhIRElATllVYWQxOC0yMiJ9fX0K
