apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  app-name: order
  app-version: 1.0.1
  team: engineering


---
#configs in a file format
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: | 
    server {
      listen    80;
      server_name   localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map
spec:
  selector:
    matchLabels:
      app: config-map
  template:
    metadata:
      labels:
        app: config-map
    spec:
      volumes: 
        - name: app-properties
          configMap:
            name: app-properties
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: config  
          projected: #this is mounting multiple configs in one directory
            sources:
              - configMap:
                  name: nginx-conf
              - configMap:
                  name: app-properties
      containers:
      - name: config-map-volumne
        volumeMounts:
          - mountPath: /etc/order/properties
            name: app-properties
      - name: config-map-volumne
        volumeMounts:
          - mountPath: /etc/order/nginx
            name: nginx-conf
          - mountPath: /etc/order/config
            name: config
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "sleep 3600"
      - name: config-map-env
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "env && sleep 3600"
        env: 
          - name: APP_VERSION
            valueFrom: 
              configMapKeyRef:
                name: app-properties
                key: app-version
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef:
                name: app-properties
                key: app-name
          - name: TEAM
            valueFrom: 
              configMapKeyRef:
                name: app-properties
                key: team
