apiVersion: v1
kind: Service
metadata:
  name: customer-node-port
  namespace: market
spec:
  type: NodePort
  selector:
    app: customer-pod
  ports:
  - port: 8009
    targetPort: 8009
    nodePort: 30001