
apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup-job
  namespace: market
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: backup
        image: busybox
        command: ["/bin/sh",  "-c"]
        args:
          - "echo 'Performing database backup...' && sleep 20"
      restartPolicy: Never
