apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: logging
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: docker-auth
      containers:
      - name: myapp
        image: winmorre/private:private-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        
