apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
spec:
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      volumes:
      - name: secret-1
        secret:
          secretName: mysecret
      containers:
      - name: secrets
        image: busybox 
        command: 
          - "sleep"
          - "3600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/secrets
            name: secret-1
        env:
          - name: K8S_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password               
